version: "3"

services:
  mailserver:
    build: .
    container_name: mailserver
    hostname: mail.example.com
    ports:
      - "25:25"
      - "143:143"
      - "110:110"
    restart: unless-stopped