server.service.name = chat
client.service.name = chatCallback

server.registry.host = 127.0.0.1
server.registry.port = 1099
server.service.port = 6969

client.registry.host = 127.0.0.1
client.registry.port = 1199
client.service.port = 9696
